== Deploying Strato on OpenShift 4.1

(Strato is an all-in-one data service for microservices, FaaS functions, etc. gRPC and HTTP interfaces: https://github.com/lucperkins/strato)


== Lab guide – draft


*oc version*

----
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.8-201907241243+785687c-dirty", GitCommit:"785687c", GitTreeState:"dirty", BuildDate:"2019-07-24T19:44:04Z", 
GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+4b86cc5", GitCommit:"4b86cc5", GitTreeState:"clean", BuildDate:"2019-07-24T19:42:25Z", 
GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
----


*Install odo*
*sudo curl -L https://github.com/openshift/odo/releases/latest/download/odo-linux-amd64 -o /usr/bin/odo && sudo chmod +x /usr/bin/odo*


*odo catalog list components*

----
NAME              PROJECT       TAGS
dotnet            openshift     1.0,1.1,2.1,2.2,latest
httpd             openshift     2.4,latest
java              openshift     8,latest
modern-webapp     openshift     10.x,latest
nginx             openshift     1.10,1.12,1.8,latest
nodejs            openshift     10,6,8,8-RHOAR,latest
perl              openshift     5.24,5.26,latest
php               openshift     7.0,7.1,7.2,latest
python            openshift     2.7,3.5,3.6,latest
ruby              openshift     2.3,2.4,2.5,latest
----


== Install Go toolset


*sudo subscription-manager register --user <user>*
*sudo subscription-manager list --available*
*sudo subscription-manager attach --pool <pool ID>*

*sudo subscription-manager repos --enable rhel-7-server-devtools-rpms*
*sudo yum update*
*sudo yum install -y go-toolset-1.11*


== Create golang imagestream


*curl -kL https://raw.githubusercontent.com/marcredhat/golang/master/imagestream 2> /dev/null | oc apply -n openshift --as system:admin -f -*


*odo catalog list component*

----
NAME              PROJECT       TAGS
dotnet            openshift     1.0,1.1,2.1,2.2,latest
golang            openshift     1.11,latest
httpd             openshift     2.4,latest
java              openshift     8,latest
modern-webapp     openshift     10.x,latest
nginx             openshift     1.10,1.12,1.8,latest
nodejs            openshift     10,6,8,8-RHOAR,latest
perl              openshift     5.24,5.26,latest
php               openshift     7.0,7.1,7.2,latest
python            openshift     2.7,3.5,3.6,latest
ruby              openshift     2.3,2.4,2.5,latest
----


== Deploy Strato


*oc new-project strato*

*git clone https://github.com/lucperkins/strato.git*

*cd strato*

*mkdir -p .s2i/bin/*

*wget https://raw.githubusercontent.com/marcredhat/golang/master/assemble -O .s2i/bin/assemble*

*chmod +x .s2i/bin/assemble*

*odo create golang strato --project strato --port 8081 --env INSTALL_URL=github.com/lucperkins/strato/cmd/strato-http --env IMPORT_URL=github.com/lucperkins/strato*

*odo url create strato  --port 8081*


*odo push*

----
 ✓  Creating project strato
 ✓  Successfully created project strato
Validation
 ✓  Checking component [18ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [93ms]
 ✓  Applying configuration [18983ns]

Applying URL changes
 ✓  URL strato: http://<> created

Pushing to component strato of type local
 ✓  Checking files for pushing [13ms]
 ✓  Waiting for component to start [38s]
 ✓  Copying files to component [6s]
 ✓  Building component [1m]
 ✓  Changes successfully pushed to component
----


*odo push --show-log*

----
Validation
 ✓  Checking component [22ms]

Configuration changes
 ✓  Applying configuration [75ms]

Applying URL changes
 ✓  URL strato already exists

Pushing to component strato of type local
 ✓  Checking file changes for pushing [16ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

